name: test

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        git config --global user.email "github-actions[bot]@users.noreply.github.com'"
        git config --global user.name "github-actions[bot]"
        
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    - name: Organize files
      id: organize
      continue-on-error: true
      run: |
        shopt -s extglob
        cd /workdir
        mkdir tmp
        
        dd if=/dev/zero of=file bs=1M count=10000
        split -b 1000m -d -a 2 file tmp/file
        ls -l
        
    - name: Delete current release assets
      uses: andreaswilli/delete-release-assets-action@v2.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: PackagesCache
        deleteOnlyFromDrafts: false
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /workdir/tmp/*
        tag: PackagesCache
        overwrite: true
        file_glob: true
        
        
