name: test

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        git config --global user.email "github-actions[bot]@users.noreply.github.com'"
        git config --global user.name "github-actions[bot]"
        
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    - name: Organize files
      id: organize
      continue-on-error: true
      run: |
        shopt -s extglob
        cd /workdir
        mkdir tmp
        cd tmp
        seq 12 | xargs -i dd if=/dev/zero of=file{} bs=1M count=1000
        ls -l
    
    - name: Deploy Caches to Driver
      run: |
        rclone sync -P --transfers=10 --onedrive-chunk-size=128000k /workdir/tmp od:tmp  
        
